#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for lero
#
# IDENTIFICATION
#    src/backend/lero/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/lero
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	utils.o \
	yyjson.o \
	lero_extension.o

include $(top_srcdir)/src/backend/common.mk
